config/routes.rb
Rails.application.routes.draw do
  scope module: :web, as: :web do
    root to: 'root#index'

    resource :sign_in, only: %i[show]
    resources :authentications, only: %i[create destroy]

    resources :users, only: %i[index show new create] do
      scope module: :users do
        resources :microposts, only: %i[index]
        resources :followers,  only: %i[index]
        resources :followings, only: %i[index]
      end
    end

    scope module: :authentication do
      resources :microposts, only: %i[new create destroy]
      resource :timeline, only: %i[show]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts
  has_many :user_followings, class_name: 'UserFollow', foreign_key: :follower_id, dependent: :destroy
  has_many :followings, class_name: 'User', through: :user_followings, source: :user
  has_many :user_follows, dependent: :destroy
  has_many :followers, class_name: 'User', through: :user_follows, source: :follower

  has_secure_password

  validates :given_name, presence: true
  validates :family_name, presence: true
  validates :email_address, presence: true
  # TODO: email format
end

app/models/user_follow.rb
class UserFollow < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web/authentication/microposts_controller.rb
class Web::Authentication::MicropostsController < ::Web::AuthenticationController
  before_action :set_micropost, only: %i[destroy]

  # GET /microposts/new
  def new
    @micropost = current_user.microposts.build
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)

    if @micropost.save
      redirect_to @micropost, notice: 'Micropost was successfully created.'
    else
      render :new
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = current_user.microposts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/controllers/web/authentication/timelines_controller.rb
# frozen_string_literal: true

class Web::Authentication::TimelinesController < ::Web::AuthenticationController
  def show
    following_user_ids = current_user.user_followings.pluck(:user_id)
    @microposts = Micropost.where(user_id: following_user_ids).preload(:user).order(created_at: :desc)
  end
end

app/controllers/web/authentication_controller.rb
# frozen_string_literal: true

class Web::AuthenticationController < ::WebController
  private

  def current_user
    # TODO: hoge
    @current_user ||= User.find(1)
  end
end

app/controllers/web/microposts_controller.rb
class Web::MicropostsController < Web::UserController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = current_user.microposts
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = current_user.microposts.build
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = current_user.microposts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:user_id, :content)
    end
end

app/controllers/web/root_controller.rb
class Web::RootController < ::WebController
  def index
  end
end

app/controllers/web/user_controller.rb
# frozen_string_literal: true

class Web::UserController < ApplicationController
  private

  def current_user
    # TODO: hoge
    @current_user ||= User.find(1)
  end
end

app/controllers/web/users_controller.rb
# frozen_string_literal: true

class Web::UsersController < ::WebController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/web_controller.rb
# frozen_string_literal: true

class WebController < ApplicationController
  protect_from_forgery with: :exception
end

app/views/layouts/bulma.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset='UTF-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/web.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset='UTF-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>RailsTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web/authentication/microposts/_form.html.slim
= form_for @micropost do |f|
  - if @micropost.errors.any?
    #error_explanation
      h2 = "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"
      ul
        - @micropost.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit

app/views/web/authentication/microposts/new.html.slim
h1 New micropost

== render 'form'

= link_to 'Back', microposts_path

app/views/web/authentication/timelines/show.html.slim
section.section
  .container
    h1 Timeline
    - @microposts.each do |micropost|
      = micropost.content

app/views/web/root/index.html.slim
h1 Root#index
p Find me in app/views/root/index.html.slim

app/views/web/users/index.html.slim
section.section
  .container
    h1 users
    - @users.each do |user|
      = link_to user.given_name, web_user_path(user)

app/views/web/users/show.html.slim
section.section
  .container
    h1= @user.given_name